language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

addons:
    ssh_known_hosts: git.coding.net

before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - sudo cp .travis/ssh_config /etc/ssh/ssh_config
    - sudo chmod 755 /etc/ssh/ssh_config
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - git config --global user.name "dmxiaoshen"
    - git config --global user.email "dmxiaoshen@163.com"

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  # - git clone https://${GH_REF} .deploy_git
  # - cd .deploy_git
  # - git checkout master
  # - cd ../
  # - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git init
  - echo "## 在那桃花盛开的地方">>README.md
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
  - rm -rf .git
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "git@git.coding.net:dmxiaoshen/dmxiaoshen.git" master:master

branches:
  only:
    - master  #只监测master分支，可根据自己情况设置分支
env:
 global:
   - GH_REF: github.com/dmxiaoshen/dmxiaoshen.github.io.git  #设置GH_REF，注意更改yourname
